---
title: "writing function"
author: "Huili Zheng"
date: "11/4/2021"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(rvest)
```


## z score

```{r}
x_vec= rnorm(25, mean = 5, sd = 4)

(x_vec - mean(x_vec)) / sd(x_vec)


z_scores = function(x){
  
  z = (x - mean(x)) / sd(x)
  
  return(z)
}

z_scores(x = x_vec)

y_vec = rnorm(40, mean = 12, sd = .3)

z_scores(x = y_vec)
```


How great is this ?

only kinda great.

let's try again.


```{r, error=TRUE}
z_scores = function(x){
  
  if (!is.numeric(x)){
    stop("x needs to be numeric")
  }
  
  if (length(x)<3){
    stop("x should be at least 3 numbers")
  }
  
  z = (x - mean(x)) / sd(x)
  
  return(z)
}


z_scores(3)

z_scores(c("my","name","is","hu"))

z_scores(mtcars)

z_scores(x = y_vec)
```

## multiple outputs

```{r}
mean_and_sd = function(x){
  
  if (!is.numeric(x)){
    stop("x needs to be numeric")
  }
  
  if (length(x)<3){
    stop("x should be at least 3 numbers")
  }
  
  mean_x = mean(x)
  sd_x = sd(x)
  
  #create an output tibble
  output_df = 
    tibble(
      mean = mean_x,
      sd = sd_x
    )
  
  return(output_df)
}

mean_and_sd(y_vec)
```


## different sample sizes, means, sds

```{r}
sim_data = 
  tibble(
    x = rnorm(30, mean = 2, sd = 3)
  )

sim_data %>%
  summarise(
    mean = mean(x),
    sd = sd(x)
  )
```

let's write a function that simulates data, computes the mean and sd.

```{r}
sim_mean_sd = function(n, mu, sigma){
  
  # do checks on inputs
  
sim_data = 
  tibble(
    x = rnorm(n, mean = mu, sd = sigma)
  )

sim_data %>%
  summarise(
    mean = mean(x),
    sd = sd(x)
  )
}

sim_mean_sd(30,4,3)

```

